### ISSUE TITLE
Update Documentation regarding file table

### ISSUE THREAD

**Issue by LasKru** [monagrland/MB_Pipeline#15]
Release 2.0 changed the way the input files are defined in the config file. Previously it was just a string with a path to the directory, now it needs a path to a tsv table. The documentation is missing information on how this table needs to be build. 

The documentation needs to be updated and ideally an example table added. There is a table already available in the "test/" directory, but there is no information available on what the "lib" column is supposed to contain.

**Comment by kbseah** [comment]
Addressed in commit 3c1372e86
